### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by liujialun** [zenorocha/select#9]
package.json

---"main":"src/select.js"
----------------------------------
should be:
--"main":"dist/select.js"

**Comment by zenorocha** [comment]
Closing since no explanation was provided.

**Comment by scriptype** [comment]
Actually I think this is a valid report, even though the title doesn't say too much.

I'm getting `"module" is not defined` error in my console (I'm not using a module bundler), and I think it's because select.js points to un-browserified source code.

p.s. FYI, I'm fetching it from: https://unpkg.com/select@1.1.2/src/select.js
